In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
dataset = pd.read_csv('Data.csv')

In [3]:
dataset.head()

States   Age   Salary Purchased
0       Texas  44.0  72000.0        No
1     Florida  27.0  48000.0       Yes
2  California  30.0  54000.0        No
3       Texas  38.0  61000.0        No
4  California   NaN  65000.0       Yes

In [4]:
dataset.tail()

States   Age   Salary Purchased
5       Texas  35.0  58000.0       Yes
6  California  40.0      NaN        No
7       Texas  48.0  79000.0       Yes
8     Florida  50.0  83000.0        No
9       Texas  37.0  67000.0       Yes

In [5]:
X = dataset.iloc[: , :-1].values

In [6]:
y = dataset.iloc[: , -1].values

In [7]:
X

array([['Texas', 44.0, 72000.0],
       ['Florida', 27.0, 48000.0],
       ['California', 30.0, 54000.0],
       ['Texas', 38.0, 61000.0],
       ['California', nan, 65000.0],
       ['Texas', 35.0, 58000.0],
       ['California', 40.0, nan],
       ['Texas', 48.0, 79000.0],
       ['Florida', 50.0, 83000.0],
       ['Texas', 37.0, 67000.0]], dtype=object)

In [8]:
#handling the missimg values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan , strategy = 'mean')
X[: , 1:3] = imputer.fit_transform(X[: , 1:3])

In [10]:
X

array([['Texas', 44.0, 72000.0],
       ['Florida', 27.0, 48000.0],
       ['California', 30.0, 54000.0],
       ['Texas', 38.0, 61000.0],
       ['California', 38.77777777777778, 65000.0],
       ['Texas', 35.0, 58000.0],
       ['California', 40.0, 65222.22222222222],
       ['Texas', 48.0, 79000.0],
       ['Florida', 50.0, 83000.0],
       ['Texas', 37.0, 67000.0]], dtype=object)

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encode' , OneHotEncoder() , [0])] , remainder = 'passthrough')
X = ct.fit_transform(X)

In [12]:
X

array([[0.0, 0.0, 1.0, 44.0, 72000.0],
       [0.0, 1.0, 0.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 38.77777777777778, 65000.0],
       [0.0, 0.0, 1.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 40.0, 65222.22222222222],
       [0.0, 0.0, 1.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 1.0, 37.0, 67000.0]], dtype=object)

In [13]:
X = X[: , 1:]#avoiding the dummy variable trap

In [14]:
X

array([[0.0, 1.0, 44.0, 72000.0],
       [1.0, 0.0, 27.0, 48000.0],
       [0.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 38.77777777777778, 65000.0],
       [0.0, 1.0, 35.0, 58000.0],
       [0.0, 0.0, 40.0, 65222.22222222222],
       [0.0, 1.0, 48.0, 79000.0],
       [1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 37.0, 67000.0]], dtype=object)

In [15]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(X , y , test_size=0.2, random_state = 0)

In [16]:
x_train

array([[0.0, 0.0, 38.77777777777778, 65000.0],
       [0.0, 1.0, 37.0, 67000.0],
       [1.0, 0.0, 27.0, 48000.0],
       [0.0, 0.0, 40.0, 65222.22222222222],
       [0.0, 1.0, 48.0, 79000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 44.0, 72000.0],
       [0.0, 1.0, 35.0, 58000.0]], dtype=object)

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [18]:
x_train

array([[-0.37796447, -1.29099445,  0.05261351,  0.06895002],
       [-0.37796447,  0.77459667, -0.25350148,  0.29985242],
       [ 2.64575131, -1.29099445, -1.97539832, -1.89372037],
       [-0.37796447, -1.29099445,  0.26306757,  0.09460584],
       [-0.37796447,  0.77459667,  1.64058505,  1.68526682],
       [-0.37796447,  0.77459667, -0.0813118 , -0.39285478],
       [-0.37796447,  0.77459667,  0.95182631,  0.87710842],
       [-0.37796447,  0.77459667, -0.59788085, -0.73920837]])

In [ ]:
#Thank you